env:
    token_telegram: "ENCRYPTED[1c93d2fc5120b1bc4e4c22881857145aca9fcf047735a11cca4d602b7372c01c6a8f5e9663fcb732ff8d4cb44787a8ec]"
    id_telegram: "ENCRYPTED[5c057df3fef290e80e278e996ecd4992ade3caf260c0a048c09fa2b04a03623bccf49f6d043d878ab6ee4b68c8ae96a5]"
    rclone_config: "ENCRYPTED[77edbce3e69b5ec935f81fd1c48a21895a5eadde5586d6ef1af12f892ce0510418d199485bc6919b57a640c34e514328]"

task:
    name: DerpFest
    timeout_in: 120m
    container:
      image: inok2341/anu:latest
      cpu: 8
      memory: 32G      

    mengunduh_ccache_background_script:
      - mkdir -p ~/.config/rclone
      - echo "$rclone_config" > ~/.config/rclone/rclone.conf
      - df -h && free -h && nproc && cat /etc/os* && env
      - mkdir -p /tmp/ccache
      - rclone copy rcloneidp:derpfest/ccache.tar.gz /tmp -P
      - cd /tmp
      - time tar xf ccache.tar.gz
      - ls /tmp
      - ls /tmp/ccache
      - rm -rf ccache.tar.gz
      - mkdir -p /tmp/rom
      - cd /tmp/rom
      - export CCACHE_DIR=/tmp/ccache
      - export CCACHE_EXEC=$(which ccache)
      - export USE_CCACHE=1
      - ccache -M 20G
      - ccache -o compression=true
      - ccache -z
    memantau_background_script:
      - ./memantau
    mengsinkronisasi_script:
      - ./sinkronisasi
#    mengumpulkan_ccache_script:
#     - ./mengumpulkan_ccache
    membangun_akhir_script:
     - ./membangun_akhir
    mengunggah_script:
      - ./mengunggah

