#!/bin/bash


cd /tmp

com () 
{ 
    tar --use-compress-program="pigz -k -$2 " -cf $1.tar.gz $1
}

time com ccache 1

cd /tmp
time rclone copy /tmp/rom/out/target/product/juice/evolution_juice-*.zip darx:juice -P
cd /tmp/rom/out/target/product/juice/
curl -s "https://api.telegram.org/bot${token_telegram}/sendmessage" --data "text=Download Link -> https://lightnest.darknius09.workers.dev/juice/$(ls evolution_juice*.zip)=${id_telegram}&parse_mode=html"
cd /tmp
time rclone copy ccache.tar.gz darx:evox12 -P
