#!/bin/bash

cd /tmp/rom

# sync
repo init -q --no-repo-verify --depth=1 -u https://github.com/Evolution-X/manifest -b snow -g default,-device,-mips,-darwin,-notdefault
repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j8

# Trees
git clone --depth=1 https://github.com/Night-Raids-Reborn/dt-juice -b evox device/xiaomi/juice
git clone --depth=1 https://github.com/Night-Raids-Reborn/vendor_xiaomi_juice --single-branch -b snow vendor/xiaomi/juice
git clone --depth=1 https://github.com/darknius20/guuji_kernel_juice --single-branch -b main.stbl kernel/xiaomi/juice

